services:
  postgres-db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: splitwise_db
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
volumes:
  postgres_data: